#!/usr/bin/env fish

curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

# Plugins
fisher install jorgebucaran/nvm.fish
fisher install PatrickF1/fzf.fish

# Theme
fish_config theme choose "Mono Lace"
