#!/bin/bash
# Generates an alacritty color config from currently loaded X resources.

xresource() {
	xrdb -query | grep -E '^\*.'"$1"':'
}

color_from_line() {
	read -r line
	echo "${line}" | tr -d '[:space:]' | cut -d ':' -f 2
}

readonly color_idx=(black red green yellow blue magenta cyan white)

# Begin to print alacritty config.
printf 'colors:\n'
printf '    primary:\n'
printf '        background: "%s"\n' "$(xresource 'background' | color_from_line)"
printf '        foreground: "%s"\n' "$(xresource 'foreground' | color_from_line)"

declare -i i=0
while read -r line; do
	if [[ $i == 0 ]]; then
		printf '    normal:\n'
	fi

	if [[ $i == 8 ]]; then
		printf '    bright:\n'
	fi

	printf '        %s: "%s"\n' \
		"${color_idx[((i % 8))]}" \
		"$(echo "$line" | color_from_line)"

	i+=1
done < <(xresource 'color[[:digit:]]+' | sort -V)
