# import = [
	"~/.config/alacritty/theme.toml",
	"~/.config/alacritty/keybindings.toml"
	"~/.config/alacritty/schemes/simple.toml",
#	"~/.config/alacritty/schemes/base16_dark.toml",
#	"~/.config/alacritty/schemes/gruvbox.toml",
#	"~/.config/alacritty/schemes/gruvbox_dark.toml",
#	"~/.config/alacritty/schemes/onehalf_dark.toml",
#	"~/.config/alacritty/schemes/xteml.toml"
# ]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xFFFFFF"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "on"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
regex = "(https:|http:)[^\u0000-\u001F\u007F-<>\" {-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
decorations_theme_variant = "Light"

[window.padding]
x = 3
y = 3
