[keyboard]
bindings = [
    { key = "Paste",                                        action = "Paste"           },
    { key = "Copy",                                         action = "Copy"            },
    { key = "PageUp",    mods = "Shift",    mode = "~Alt",  action = "ScrollPageUp"    },
    { key = "PageDown",  mods = "Shift",    mode = "~Alt",  action = "ScrollPageDown"  },
    { key = "Home",      mods = "Shift",    mode = "~Alt",  action = "ScrollToTop"     },
    { key = "End",       mods = "Shift",    mode = "~Alt",  action = "ScrollToBottom"  },

    # (Windows, Linux, and BSD only)
    { key = "V",         mods = "Control|Shift",    action = "Paste"            },
    { key = "C",         mods = "Control|Shift",    action = "Copy"             },
    { key = "F",         mods = "Control|Shift",    action = "SearchForward"    },
    { key = "Plus",      mods = "Control",          action = "IncreaseFontSize" },
    { key = "Minus",     mods = "Control",          action = "DecreaseFontSize" },

    # Vim mode
    { key = "Space",     mods = "Shift|Control",                action = "ToggleViMode"            },
    { key = "G",                                 mode = "Vi",   action = "ScrollToTop"             },
    { key = "I",                                 mode = "Vi",   action = "ToggleViMode"            },
    { key = "C",         mods = "Control",       mode = "Vi",   action = "ToggleViMode"            },
    { key = "G",         mods = "Shift",         mode = "Vi",   action = "ScrollToBottom"          },
    { key = "K",                                 mode = "Vi",   action = "Up"                      },
    { key = "J",                                 mode = "Vi",   action = "Down"                    },
    { key = "H",                                 mode = "Vi",   action = "Left"                    },
    { key = "L",                                 mode = "Vi",   action = "Right"                   },
    { key = "Up",                                mode = "Vi",   action = "Up"                      },
    { key = "Down",                              mode = "Vi",   action = "Down"                    },
    { key = "Left",                              mode = "Vi",   action = "Left"                    },
    { key = "Right",                             mode = "Vi",   action = "Right"                   },
    { key = "Slash",                             mode = "Vi",   action = "SearchForward"           },
    { key = "N",                                 mode = "Vi",   action = "SearchNext"              },
    { key = "N",         mods = "Shift",         mode = "Vi",   action = "SearchPrevious"          },
    { key = "V",         mods = "Shift",         mode = "Vi",   action = "ToggleLineSelection"     },
    { key = "V",         mods = "Control",       mode = "Vi",   action = "ToggleBlockSelection"    },
    { key = "V",         mods = "Alt",           mode = "Vi",   action = "ToggleSemanticSelection" },
    { key = "Y",                                 mode = "Vi",   action = "Copy"                    },
    { key = "Y",                                 mode = "Vi",   action = "ClearSelection"          },
    { key = "Copy",                              mode = "Vi",   action = "ClearSelection"          },
]
