[color.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fe25bc"
yellow = "#fabd2f"

[color.normal]
black = "#504945"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#fbf1c7"
yellow = "#d79921"

[color.primary]
background = "#1d2021"
