[color.bright]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#dcdfe4"
yellow = "#e5c07b"

[color.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#dcdfe4"
yellow = "#e5c07b"

[color.primary]
background = "#282c34"
foreground = "#dcdfe4"
